language: c
sudo: required
dist: trusty
compiler: clang
before_install:
- curl https://letsencrypt.org/certs/isrgrootx1.pem.txt | sudo tee /usr/share/ca-certificates/isrgrootx1.crt
- echo "isrgrootx1.crt" | sudo tee -a /etc/ca-certificates.conf
- curl https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt | sudo tee
  /usr/share/ca-certificates/lets-encrypt-x3-cross-signed.crt
- echo "lets-encrypt-x3-cross-signed.crt" | sudo tee -a /etc/ca-certificates.conf
- sudo update-ca-certificates
- curl https://raw.githubusercontent.com/bbcarchdev/bbcarchdev-keys/main/bbcarchdev-apt.asc
  | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://apt.bbcarchdev.net/debian wheezy
  main ports dev stage live"
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)
  main universe restricted multiverse"
- sudo apt-get update -qq
- sudo apt-get install -qq libtwine-dev uuid-dev liburi-dev libsql-dev libsparqlclient-dev
  libawsclient-dev libmq-dev automake autoconf libtool pkg-config
before_script:
- autoreconf -f -i
script:
- ./configure && make && make check
notifications:
  slack:
    secure: KQg52IuFEeiMtl0NO328q42HH1qY2sc619FxGzxszY9G0rumEozYxDf+cNu0LiDZoJH9ecaSHbA96CKLz+myNPZOUXDgXH49ZsDV6YDG7FvYfV8PoUNE8bztKymOsAHkQpT6SetJ0QI2EJrDQZ3vyruQe8E3B3SjtzmfwKVlQJQ=
