#!/bin/bash

cc strset_test.c -o strset_test -lcgreen && ./strset_test
cc rulebase_test.c -o rulebase_test -lcgreen && ./rulebase_test
cc rulebase_cachepred_test.c -o rulebase_cachepred_test -lcgreen && ./rulebase_cachepred_test
cc rulebase_class_test.c -o rulebase_class_test -lcgreen && ./rulebase_class_test
cc rulebase_coref_test.c -o rulebase_coref_test -lcgreen && ./rulebase_coref_test
cc rulebase_pred_test.c -o rulebase_pred_test -lcgreen && ./rulebase_pred_test
